Metrics/LineLength:
  Max: 120
Documentation:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.5
## Defaults from rubocop
Style/PercentLiteralDelimiters:
  # Specify the default preferred delimiter for all types with the 'default' key
  # Override individual delimiters (even with default specified) by specifying
  # an individual key
  PreferredDelimiters:
    default: ()
    '%i': '[]'
    '%I': '[]'
    '%r': '{}'
    '%w': '[]'
    '%W': '[]'
